language: php

php:
    - 7.1
    - master

env:
    coverage=on

matrix:
    allow_failures:
        - php: master

script:
    - vendor/bin/tester tests -s $coverageArgs
    - php temp/code-checker/src/code-checker.php --short-arrays --strict-types

before_script:
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker temp/code-checker ~2.8 --no-interaction
    - if [ "$coverage" == "on" ]; then coverageArgs="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    - >
      if [ "$coverage" == "on" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml
      || true; fi

after_failure:
    - for i in $(find ./tests -name \*.expected); do echo "--- $i"; cat $i; echo; echo; done
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false
